.TH ipdb3 1
.SH NAME
ipdb3 \- standalone IPython-based Python 3 debugger
.SH SYNOPSIS
.B ipdb
\fIscriptfile \fR[\fIarg\fR]...
.br
.SH DESCRIPTION
ipdb3 is a standalone Python 3 debugger based on IPython. It is similar to the pdb
debugger from the Python standard library but has additional IPython features
such as improved tracebacks and syntax highlighting.
.SH "SEE ALSO"
pdb documentation at
\fBhttp://docs.python.org/library/pdb.html\fR
or
\fB/usr/share/doc/python/html/library/pdb.html\fR
